# Generated by Django 3.0.5 on 2021-04-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='제품 이름')),
                ('item_price', models.IntegerField(verbose_name='제품 가격')),
                ('item_company', models.CharField(max_length=255, verbose_name='제품 회사')),
                ('item_stock', models.IntegerField(verbose_name='제품 재고')),
                ('item_image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='제품 이미지')),
                ('item_content', models.TextField(verbose_name='제품 설명')),
            ],
        ),
    ]
