# Generated by Django 3.0.5 on 2021-04-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminfo',
            options={'verbose_name_plural': '제품 정보'},
        ),
    ]
